export enum Constants {
    ADD_PRODUCT = 'ADD PRODUCT',
    DELETE_PRODUCT = 'DELETE PRODUCT',
    ADD_PRODUCT_COUNT = 'ADD PRODUCT COUNT',
    REDUCE_PRODUCT_COUNT = 'REDUCE PRODUCT COUNT',
    ADD_PRICE = 'ADD PRICE',
    REDUCE_PRICE = 'REDUCE PRICE',
    RESTART_COUNT = 'RESTART COUNT'
}



